"""Protocol and interface definitions for the application.

All services and repositories should conform to these protocols
to enable loose coupling, testability, and future hot-swapping.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from models.domain import (
    MemoryProfile,
    Message,
    ModelRegistryEntry,
    RouterDecision,
    UserFact,
    Workspace,
)
from models.enums import RouterMode


@runtime_checkable
class RepositoryProtocol(Protocol):
    def close(self) -> None: ...


@runtime_checkable
class ChatRepositoryProtocol(RepositoryProtocol, Protocol):
    def save_for_chat(self, chat_id: int, role: str, content: str) -> int: ...
    def get_by_token_budget(self, chat_id: int, budget: int) -> list[Message]: ...
    def total_tokens_for_chat(self, chat_id: int) -> int: ...
    def clear_for_chat(self, chat_id: int) -> None: ...


@runtime_checkable
class ModelManagerProtocol(Protocol):
    def get_available(self) -> list[str]: ...
    def get_active(self) -> str | None: ...
    def set_active(self, name: str) -> None: ...
    def refresh_available(self) -> list[str]: ...
    def get_registry_entry(self, name: str) -> ModelRegistryEntry | None: ...
    def is_api_model(self, name: str) -> bool: ...
    def invalidate_cache(self, name: str) -> None: ...


@runtime_checkable
class ModelRouterProtocol(Protocol):
    def route(self, message: str, fallback_model: str) -> RouterDecision: ...
    def get_mode(self) -> RouterMode: ...
    def set_mode(self, mode: RouterMode) -> None: ...
    def set_workspace_category(self, category: str | None) -> None: ...


@runtime_checkable
class MemoryServiceProtocol(Protocol):
    def search(self, query: str, limit: int = 5) -> list[UserFact]: ...
    def add_fact(self, key: str, value: str, importance: int = 5) -> None: ...
    def delete_fact(self, fact_id: int) -> bool: ...
    def get_all_facts(self) -> list[UserFact]: ...
    def get_all_profiles(self) -> list[MemoryProfile]: ...
    def rebuild_index(self) -> None: ...


@runtime_checkable
class SummarizationServiceProtocol(Protocol):
    def run_pipeline(self, messages: list[Message], chat_id: int | None = None) -> None: ...


@runtime_checkable
class WorkspaceServiceProtocol(Protocol):
    def get_active(self) -> Workspace | None: ...
    def get_all(self) -> list[Workspace]: ...
    def switch(self, name: str) -> tuple[bool, str]: ...
    def update_active_model(self, model: str) -> None: ...
    def update_active_router(self, mode: RouterMode) -> None: ...
    def update_active_memory_profile(self, profile_id: int | None) -> None: ...


@runtime_checkable
class VectorStoreProtocol(Protocol):
    def search(self, query: str, limit: int = 5) -> list[UserFact]: ...
    def rebuild(self, facts: list[UserFact]) -> None: ...
    def close(self) -> None: ...
