"""Markdown report generation for validation results."""

from __future__ import annotations

from datetime import datetime

from core.environment.models import Severity, ValidationReport, ValidationResult


def generate_report_markdown(report: ValidationReport) -> str:
    """Generate a human-readable markdown environment validation report."""
    lines: list[str] = []
    lines.append("# Environment Validation Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Duration:** {report.execution_time:.3f}s")
    lines.append(f"**Overall Status:** {'HEALTHY' if report.is_healthy else 'UNHEALTHY'}")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| Passed | {len(report.passed)} |")
    lines.append(f"| Warnings | {len(report.warnings)} |")
    lines.append(f"| Errors | {len(report.errors)} |")
    lines.append(f"| Critical | {len(report.critical)} |")
    lines.append(f"| **Total** | **{len(report.results)}** |")
    lines.append("")

    for result in report.results:
        lines.append("---")
        lines.append("")
        lines.append(f"### {_status_icon(result)} {result.name}")
        lines.append("")
        lines.append(f"**Status:** {'PASS' if result.success else 'FAIL'}")
        lines.append(f"**Severity:** {result.severity.value}")
        lines.append(f"**Message:** {result.message}")
        lines.append("")

        if result.details:
            lines.append("**Details:**")
            lines.append("")
            lines.append("```")
            for key, value in _format_details(result.details).items():
                lines.append(f"  {key}: {value}")
            lines.append("```")
            lines.append("")

        if result.recommendation:
            lines.append(f"**Recommendation:** {result.recommendation}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by Environment Validation Framework*")

    return "\n".join(lines)


def _status_icon(result: ValidationResult) -> str:
    if result.success:
        if result.severity == Severity.WARNING:
            return "(i)"
        return "(v)"
    if result.severity == Severity.CRITICAL:
        return "(!)"
    if result.severity == Severity.ERROR:
        return "(x)"
    return "(i)"


def _format_details(details: dict) -> dict[str, str]:
    """Flatten nested dicts to readable strings, truncating long values."""
    formatted: dict[str, str] = {}

    for key, value in details.items():
        if isinstance(value, dict):
            formatted[key] = _summarize_dict(value)
        elif isinstance(value, list):
            if all(isinstance(item, str) for item in value):
                formatted[key] = ", ".join(value)
            elif len(value) > 10:
                formatted[f"{key} (count)"] = str(len(value))
                for i, item in enumerate(value[:5]):
                    sub_key = f"  [{i}]"
                    if isinstance(item, dict):
                        for sk, sv in item.items():
                            if not isinstance(sv, (dict, list)):
                                formatted[f"{sub_key}.{sk}"] = _truncate(str(sv))
                    else:
                        formatted[sub_key] = _truncate(str(item))
            else:
                for i, item in enumerate(value):
                    sub_key = f"  [{i}]"
                    if isinstance(item, dict):
                        for sk, sv in item.items():
                            if not isinstance(sv, (dict, list)):
                                formatted[f"{sub_key}.{sk}"] = _truncate(str(sv))
                    else:
                        formatted[sub_key] = _truncate(str(item))
        else:
            formatted[key] = _truncate(str(value))

    return formatted


def _summarize_dict(d: dict, max_keys: int = 10) -> str:
    keys = list(d.keys())[:max_keys]
    parts = []
    for k in keys:
        v = d[k]
        if not isinstance(v, (dict, list)):
            parts.append(f"{k}={v}")
    suffix = f" ... and {len(d) - max_keys} more" if len(d) > max_keys else ""
    return f"{{{', '.join(parts)}{suffix}}}"


def _truncate(value: str, max_len: int = 120) -> str:
    return value if len(value) <= max_len else value[: max_len - 3] + "..."
